#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const rulesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "rules");
const outFile = join(rulesDir, "all.grit");

const HEADER_RE = /^\s*(engine|language)\b/;

/*
 * Each individual rule file starts with one or more directive lines (`engine`
 * and/or `language`) followed by a single top-level pattern. To merge them into
 * one file we emit the shared directives once and wrap every pattern body as an
 * arm of a top-level `or { ... }`. Biome requires all merged rules to share the
 * same language, so divergent directives are a hard error rather than a silent
 * mismerge.
 */
function parse(source) {
  const lines = source.split("\n");
  const header = [];
  let i = 0;
  while (
    i < lines.length &&
    (HEADER_RE.test(lines[i]) || lines[i].trim() === "")
  ) {
    if (HEADER_RE.test(lines[i])) {
      header.push(lines[i].trim());
    }
    i++;
  }
  const body = lines.slice(i).join("\n").trim();
  return { header: header.join("\n"), body };
}

const files = readdirSync(rulesDir)
  .filter((name) => name.endsWith(".grit") && name !== "all.grit")
  .sort();

if (files.length === 0) {
  throw new Error(`No source .grit rules found in ${rulesDir}`);
}

let sharedHeader = null;
const arms = [];

for (const name of files) {
  const { header, body } = parse(readFileSync(join(rulesDir, name), "utf8"));
  if (sharedHeader === null) {
    sharedHeader = header;
  } else if (header !== sharedHeader) {
    throw new Error(
      `Rule "${name}" declares a different language/engine header than the others.\n` +
        `Expected:\n${sharedHeader}\nGot:\n${header}\n` +
        "All rules merged into all.grit must target the same language."
    );
  }
  if (body === "") {
    throw new Error(`Rule "${name}" has no pattern body.`);
  }
  arms.push(
    body
      .split("\n")
      .map((line) => (line ? `  ${line}` : line))
      .join("\n")
  );
}

const banner =
  "// AUTO-GENERATED by scripts/generate-all.mjs — do not edit.\n" +
  "// Combines every rule in rules/*.grit. Run `pnpm build` to regenerate.\n";

const output = `${banner}\n${sharedHeader}\n\nor {\n${arms.join(",\n")}\n}\n`;

writeFileSync(outFile, output);
console.log(`Wrote ${outFile} (${files.length} rules: ${files.join(", ")})`);
